// <auto-generated />
namespace PassionProjectASP.NETNajibOsman.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class playercommunity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(playercommunity));
        
        string IMigrationMetadata.Id
        {
            get { return "202302150554075_player-community"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
